version: '3'
services:

  # servicios de clientes ---------
  clientes:
    build:
      context: ./clientes
    volumes:
      - ./clientes:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - PORT_MONGO=27018
      - URL_MONGO=mongo-clientes
      - PORT=3000
    links:
      - mongo-clientes
    depends_on:
      - mongo-clientes
      
  mongo-clientes:
    image: mongo
    command: mongod --port 27018
    container_name: "mongo-clientes"
    ports:
      - 27018:27018
    volumes:
      - ./clientes/data/db:/data/db
  # servicios de clientes ---------

  # servicios de servicios ---------
  servicios:
    build: 
      context: ./servicios
    volumes:
      - ./servicios:/app
    ports:
      - 3333:3333
    environment:
      - PORT_MONGO=27017
      - URL_MONGO=mongo-servicios
      - PORT=3333
    links:
      - mongo-servicios
    depends_on:
      - mongo-servicios    

  mongo-servicios:
    image: mongo
    command: mongod --port 27017
    container_name: "mongo-servicios"
    ports:
      - 27017:27017
    volumes:
      - ./servicios/data/db:/data/db
  # servicios de servicios ---------

  # servicios de suscripciones ---------
  suscripciones:
    build: 
      context: ./suscripciones
    volumes:
      - ./suscripciones:/app
      - ./suscripciones/node_modules:/app/node_modules
    ports:
      - 4567:4567
    environment:
      - PORT_MONGO=27020
      - URL_MONGO=mongo-suscripciones
      - PORT=4567
      - IP_CLIENTES_SERVICES=clientes
      - PORT_CLIENTES_SERVICES=3000
      - IP_SERVICIOS_SERVICES=servicios
      - PORT_SERVICIOS_SERVICES=3333
    links:
      - mongo-suscripciones
      - clientes
      - servicios
    depends_on:
      - mongo-suscripciones
      - clientes
      - servicios
      
  mongo-suscripciones:
    image: mongo
    command: mongod --port 27020
    container_name: "mongo-suscripciones"
    ports:
      - 27020:27020
    volumes:
      - ./suscripciones/data/db:/data/db
  # servicios de suscripciones ---------

  # servicios de facturas ---------
  facturas:
    build: 
      context: ./facturas
    volumes:
      - ./facturas:/app
    ports:
      - 5678:5678
    environment:
      - PORT_MONGO=27030
      - URL_MONGO=mongo-facturas
      - PORT=5678
      - IP_SUSCRIPCIONES_SERVICES=suscripciones
      - PORT_SUSCRIPCIONES_SERVICES=4567
    links:
      - mongo-facturas
      - suscripciones
    depends_on:
      - mongo-facturas 
      - suscripciones

  mongo-facturas:
    image: mongo
    command: mongod --port 27030
    container_name: "mongo-facturas"
    ports:
      - 27030:27030
    volumes:
      - ./facturas/data/db:/data/db
  # servicios de facturas ---------

networks:
  default:
    external:
      name: job-net